// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_task_systems_ltd/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_task_systems_ltd/core/services/api/network_info.dart'
    as _i8;
import 'package:flutter_task_systems_ltd/features/products/data/datasources/product_local_datasource.dart'
    as _i7;
import 'package:flutter_task_systems_ltd/features/products/data/datasources/product_remote_datasource.dart'
    as _i5;
import 'package:flutter_task_systems_ltd/features/products/data/models/product_model.dart'
    as _i2;
import 'package:flutter_task_systems_ltd/features/products/domain/entities/product.dart'
    as _i3;
import 'package:flutter_task_systems_ltd/features/products/domain/repositories/product_repository.dart'
    as _i4;
import 'package:flutter_task_systems_ltd/features/products/domain/usecases/get_products.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductModel_0 extends _i1.SmartFake implements _i2.ProductModel {
  _FakeProductModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProduct_1 extends _i1.SmartFake implements _i3.Product {
  _FakeProduct_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductRepository_2 extends _i1.SmartFake
    implements _i4.ProductRepository {
  _FakeProductRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i5.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.ProductModel>> getProducts() => (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
        ),
        returnValue:
            _i6.Future<List<_i2.ProductModel>>.value(<_i2.ProductModel>[]),
      ) as _i6.Future<List<_i2.ProductModel>>);

  @override
  _i6.Future<_i2.ProductModel> getProductById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [id],
        ),
        returnValue: _i6.Future<_i2.ProductModel>.value(_FakeProductModel_0(
          this,
          Invocation.method(
            #getProductById,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.ProductModel>);
}

/// A class which mocks [ProductLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductLocalDataSource extends _i1.Mock
    implements _i7.ProductLocalDataSource {
  MockProductLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.ProductModel>> getCachedProducts() => (super.noSuchMethod(
        Invocation.method(
          #getCachedProducts,
          [],
        ),
        returnValue:
            _i6.Future<List<_i2.ProductModel>>.value(<_i2.ProductModel>[]),
      ) as _i6.Future<List<_i2.ProductModel>>);

  @override
  _i6.Future<void> cacheProducts(List<_i2.ProductModel>? products) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheProducts,
          [products],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.ProductModel?> getCachedProductById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedProductById,
          [id],
        ),
        returnValue: _i6.Future<_i2.ProductModel?>.value(),
      ) as _i6.Future<_i2.ProductModel?>);

  @override
  _i6.Future<List<int>> getFavoriteIds() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteIds,
          [],
        ),
        returnValue: _i6.Future<List<int>>.value(<int>[]),
      ) as _i6.Future<List<int>>);

  @override
  _i6.Future<void> addFavorite(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [productId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeFavorite(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [productId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isFavorite(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [productId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i4.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i3.Product>> getProducts() => (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
        ),
        returnValue: _i6.Future<List<_i3.Product>>.value(<_i3.Product>[]),
      ) as _i6.Future<List<_i3.Product>>);

  @override
  _i6.Future<_i3.Product> getProductById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [id],
        ),
        returnValue: _i6.Future<_i3.Product>.value(_FakeProduct_1(
          this,
          Invocation.method(
            #getProductById,
            [id],
          ),
        )),
      ) as _i6.Future<_i3.Product>);

  @override
  _i6.Future<List<_i3.Product>> getFavoriteProducts() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteProducts,
          [],
        ),
        returnValue: _i6.Future<List<_i3.Product>>.value(<_i3.Product>[]),
      ) as _i6.Future<List<_i3.Product>>);

  @override
  _i6.Future<void> toggleFavorite(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [productId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isFavorite(int? productId) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [productId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i8.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [GetProducts].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProducts extends _i1.Mock implements _i9.GetProducts {
  MockGetProducts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ProductRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeProductRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.ProductRepository);

  @override
  _i6.Future<List<_i3.Product>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i6.Future<List<_i3.Product>>.value(<_i3.Product>[]),
      ) as _i6.Future<List<_i3.Product>>);
}
